{
 "title": "Linky",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "pdl", "label": "Point de livraison", "query": "01226049119129" },
   { "name": "price_STD", "label": "€ / kWh Base", "query": "0.1587" },
   { "name": "price_HC", "label": "€ / kWh (HC)", "query": "0.1337" },
   { "name": "price_HP", "label": "€ / kWh (HP)", "query": "0.1781" },
   { "name": "surface_maison", "label": "Surface de la maison", "query": "240" }
  ]
 },
 "panels": [
  {
   "title": "Consommation Heures Pleines",
   "type": "singlestat",
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "alias": "PT10M",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption_load_curve",
     "query": "SELECT sum(\"value\") /60*10 FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HP' AND \"interval_length\" = 'PT10M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/60*10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "HP" },
      { "condition": "AND", "key": "interval_length", "operator": "=", "value": "PT10M" }
     ]
    },
    {
     "alias": "PT30M",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") /60*30 FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HP' AND \"interval_length\" = 'PT30M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PT60M",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HP' AND \"interval_length\" = 'PT60M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heures Pleines ($price_HP€/kWh)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption_load_curve",
     "query": "SELECT sum(\"value\")  /1000/60*10*$price_HP FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HP' AND \"interval_length\" = 'PT10M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " /1000/60*10*0.1781" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "HP" },
      { "condition": "AND", "key": "interval_length", "operator": "=", "value": "PT10M" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  /1000/60*30*$price_HP FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HP' AND \"interval_length\" = 'PT30M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  /1000*$price_HP FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HP' AND \"interval_length\" = 'PT60M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ticket Leclerc Tarif Base",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption_load_curve",
     "query": "SELECT sum(\"value\")  /1000/60*10*$price_STD* 20 / 100 FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"interval_length\" = 'PT10M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "interval_length", "operator": "=", "value": "PT10M" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  /1000/60*30*$price_STD* 20 / 100 FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"interval_length\" = 'PT30M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  /1000*$price_STD* 20 / 100 FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"interval_length\" = 'PT60M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Classe Energetique",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "consumption_load_curve",
     "query": "SELECT sum(\"value\") /60*10/$surface_maison /1000 FROM \"autogen\".\"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"interval_length\" = 'PT10M') AND time <= now() and time >= now() - 365d GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/60*10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "interval_length", "operator": "=", "value": "PT10M" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") /60*30/$surface_maison /1000 FROM \"autogen\".\"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"interval_length\" = 'PT30M') AND time <= now() and time >= now() - 365d GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")/$surface_maison /1000  FROM \"autogen\".\"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"interval_length\" = 'PT60M') AND time <= now() and time >= now() - 365d GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Répartition HC/HP",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "alias": "HP",
     "measurement": "consumption_load_curve",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "HP" }
     ]
    },
    {
     "alias": "HC",
     "measurement": "consumption_load_curve",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "HC" }
     ]
    }
   ]
  },
  {
   "title": "Consommation Heures Creuses",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption_load_curve",
     "query": "SELECT sum(\"value\")  / 60*10 FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HC' AND \"interval_length\" = 'PT10M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 60*10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "HC" },
      { "condition": "AND", "key": "interval_length", "operator": "=", "value": "PT10M" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  / 60*30 FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HC' AND \"interval_length\" = 'PT30M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")   FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HC' AND \"interval_length\" = 'PT60M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heures Creuses ($price_HC€/kWh)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption_load_curve",
     "query": "SELECT sum(\"value\")  /1000/60*10*$price_HC FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HC' AND \"interval_length\" = 'PT10M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "HC" },
      { "condition": "AND", "key": "interval_length", "operator": "=", "value": "PT10M" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  /1000/60*30*$price_HC FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HC' AND \"interval_length\" = 'PT30M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  /1000*$price_HC FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HC' AND \"interval_length\" = 'PT60M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ticket Leclerc Tarif HP/HC",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption_load_curve",
     "query": "SELECT sum(\"value\")  /1000/60*10*$price_HP*20/100 FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HP' AND \"interval_length\" = 'PT10M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " /1000/60*10*0.1781" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "HP" },
      { "condition": "AND", "key": "interval_length", "operator": "=", "value": "PT10M" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  /1000/60*30*$price_HP*20/100 FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HP' AND \"interval_length\" = 'PT30M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  /1000*$price_HP*20/100 FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HP' AND \"interval_length\" = 'PT60M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  /1000/60*10*$price_HC*20/100 FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HC' AND \"interval_length\" = 'PT10M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  /1000/60*30*$price_HC*20/100 FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HC' AND \"interval_length\" = 'PT30M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  /1000*$price_HC*20/100 FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HC' AND \"interval_length\" = 'PT60M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Période Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "consumption_load_curve",
     "query": "SELECT sum(\"value\") /60*10 FROM \"autogen\".\"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"interval_length\" = 'PT10M') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/60*10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "interval_length", "operator": "=", "value": "PT10M" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") /60*30 FROM \"autogen\".\"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"interval_length\" = 'PT30M') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"autogen\".\"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"interval_length\" = 'PT60M') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tarif HC/HP",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")   /1000/60*10*$price_HP FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HP' AND \"interval_length\" = 'PT10M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "interval_length", "operator": "=", "value": "PT10M" }
     ]
    },
    {
     "alias": "HC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")   /1000/60*10*$price_HC FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HC' AND \"interval_length\" = 'PT10M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")   /1000/60*30*$price_HP FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HP' AND \"interval_length\" = 'PT30M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")   /1000/60*30*$price_HC FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HC' AND \"interval_length\" = 'PT30M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")   /1000*$price_HP FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HP' AND \"interval_length\" = 'PT60M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")   /1000*$price_HC FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HC' AND \"interval_length\" = 'PT60M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tarif Base ($price_STD€/kWh)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption_load_curve",
     "query": "SELECT sum(\"value\")  /1000/60*10*$price_STD FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"interval_length\" = 'PT10M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "interval_length", "operator": "=", "value": "PT10M" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  /1000/60*30*$price_STD FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"interval_length\" = 'PT30M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  /1000*$price_STD FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"interval_length\" = 'PT60M') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Base vs HC/HP",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 6 },
   "format": "percent",
   "valueName": "total",
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "conso_elec",
     "query": "SELECT sum(\"value\")   /1000/60*10*$price_HP FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HP') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "HC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")   /1000/60*10*$price_HC FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"type\" = 'HC') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "STD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  / 1000/60*10*$price_STD FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Consumption - in (k)Wh",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "Consomation HP",
     "measurement": "consumption_load_curve",
     "query": "SELECT \"value\" /60*10 FROM \"autogen\".\"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "/60*10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "HP" }
     ]
    },
    {
     "alias": "Consomation HC",
     "measurement": "consumption_load_curve",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "/60*10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "HC" }
     ]
    },
    {
     "alias": "Puissance souscrite",
     "measurement": "consumption_load_curve",
     "query": "SELECT \"subscribed_power\" FROM \"autogen\".\"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "subscribed_power" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" }
     ]
    }
   ]
  },
  {
   "title": "Consommation mensuelle",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "month" ], "type": "tag" },
      { "params": [ "year" ], "type": "tag" }
     ],
     "measurement": "consumption_load_curve",
     "query": "SELECT sum(\"value\") /60*10 FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"interval_length\" = 'PT10M') GROUP BY \"month\", \"year\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/60*10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "interval_length", "operator": "=", "value": "PT10M" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") /60*30 FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"interval_length\" = 'PT30M') GROUP BY \"month\", \"year\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"interval_length\" = 'PT60M') GROUP BY \"month\", \"year\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity Consumption - per Day (k)Wh",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "Watt/Day",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "consumption_load_curve",
     "query": "SELECT value FROM \"consumption_load_curve\" WHERE (\"usage_point_id\" =~ /^$pdl$/) AND $timeFilter GROUP BY time(1d) fill(null) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" }
     ]
    }
   ]
  }
 ]
}